<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>盒老师</title>
    <meta name="keywords" content="盒老师">
    <meta name="content" content="盒老师">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <link type="text/css" rel="stylesheet" href="/public/css/login.css">
    <script type="text/javascript" src="/public/js/jquery.min.js"></script>

</head>
<body class="login_bj" >

<div class="zhuce_body">
    <div class="logo"><a href="#"><img src="/public/images/logo.png" width="114" height="54" border="0"></a></div>
    <div class="zhuce_kong">
        <div class="zc">
            <div class="bj_bai">
                <h3>欢迎注册</h3>
                <form action="" method="get">
                    <input name="username" type="text" class="kuang_txt username" placeholder="用户名">
                    <input name="possword" type="password" class="kuang_txt possword" placeholder="密码">
                    <input name="confirm_pass" type="password" class="kuang_txt confirm_pass" placeholder="确认密码">
                    <input name="注册" type="button" class="btn_zhuce" value="注册">
                </form>
            </div>
            <div class="bj_right">
                <p>使用以下账号直接登录</p>
                <a href="#" class="zhuce_qq">QQ注册</a>
                <a href="#" class="zhuce_wb">微博注册</a>
                <a href="#" class="zhuce_wx">微信注册</a>
                <p>已有账号？<a href="<?php echo BASE_URL.'/index';?>">立即登录</a></p>
            </div>
        </div>
    </div>
</div>
</body>
</html>